### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by jeroendesloovere** [mailmotor/mailmotor-bundle#2]

**Comment by jeroendesloovere** [comment]
Another approach could be https://gist.github.com/jeroendesloovere/958d5afe1f4f5b367f43

**Comment by WouterSioen** [comment]
will you give me a poke when you refactored this? I'll do a code review after you've did your changes ;)

**Comment by jeroendesloovere** [comment]
@WouterSioen Poke :-P. See "refactored-branches" in every repo
